GET http://localhost:5294/games

###
GET http://localhost:5294/games/1

###
GET http://localhost:5294/games/2

###
GET http://localhost:5294/games/3


###
GET http://localhost:5294/games/10

###
POST http://localhost:5294/games
Content-Type: application/json

{
    "name": "The Witcher 3: Wild Hunt",
    "genreId": 2,
    "price": 1999.00,
    "releaseDate": "2015-05-19"
}

###
POST http://localhost:5294/games
Content-Type: application/json

{
    "name": "Gumaji: The Lost Island",
    "genreId": 2,
    "price": 2999.00,
    "releaseDate": "2024-06-01"
}

###
POST http://localhost:5294/games
Content-Type: application/json

{
    "name": "Assassin's Creed Valhalla",
    "genreId": 1,
    "price": 2499.00,
    "releaseDate": "2020-11-10"
}

###
PUT http://localhost:5294/games/1
Content-Type: application/json

{
    "name": "Street Fighter III: 3rd Strike",
    "genreId": 1,
    "price": 1999.00,
    "releaseDate": "1999-05-19"
}


###
DELETE http://localhost:5294/games/3



